### ISSUE TITLE
Type "null" is not handled.

### ISSUE THREAD

**Issue by EmekaNkwo** [peteradeojo/typegen#2]
@peteradeojo 
When a variable type is null. It fails to generate the type for that dataset.
This happens because the check for type "null" was not handled in the generator algorithm.

Find below a pictorial representation of the bug. 
![Screenshot (6)](https://github.com/peteradeojo/typegen/assets/45833359/99a18dc2-106c-4dd3-a104-a7301c991de1)

[Link to the PR to fix this issue](https://github.com/peteradeojo/typegen/pull/1)

**Comment by peteradeojo** [comment]
Can you add a case for undefined too? and also include a screenshot of the successful output. 🙏🏽
